kind: project
spec:
  workflows:
  - name: register_raw_datasets
    path: src/workflow_register_raw_datasets.py
  source: git://github.com/jerrold110/Finetune-legal-llm-mlops.git#refs/heads/main
  functions:
  - url: src/register_raw_dataset.py
    name: raw-proc
    kind: job
    image: mlrun/mlrun
    handler: process_raw
  origin_url: git://github.com/jerrold110/Finetune-legal-llm-mlops.git#refs/heads/main
  description: A fine-tuned legal extractor LLM
  desired_state: online
  conda: ''
metadata:
  name: finetune-legal-extractor
