metadata:
  name: legalcontractextractor
kind: project
spec:
  conda: ''
  desired_state: online
  description: MLOps system for legal contractor extractor LLM
  origin_url: git://github.com/jerrold110/Finetune-legal-llm-mlops.git#refs/heads/main
  source: git://github.com/jerrold110/Finetune-legal-llm-mlops.git#refs/heads/main
