kind: project
spec:
  source: git://github.com/jerrold110/Finetune-legal-llm-mlops.git#refs/heads/main
  description: A fine-tuned legal extractor LLM
  conda: ''
  desired_state: online
  functions:
  - url: src/register_raw_dataset.py
    name: raw-proc
    kind: job
    image: mlrun/mlrun
    handler: process_raw
  - url: src/evaluate_no_train.py
    name: eval-notrain
    kind: job
    image: mlrun/mlrun
    handler: evaluate_model
  - url: src/evaluate_train.py
    name: eval-train
    kind: job
    image: mlrun/mlrun
    handler: evaluate_model_train
  origin_url: git://github.com/jerrold110/Finetune-legal-llm-mlops.git#refs/heads/main
metadata:
  name: finetune-legal-extractor
