FROM mlrun/mlrun:1.11.0

# Set environment variables

RUN python -m pip install --upgrade pip && \
    pip install -U uv

COPY requirements.txt ./tmp/requirements.txt

RUN uv pip sync ./tmp/requirements.txt

CMD ["sh", "-c", "echo Hello v1"]

