# Base SageMaker Hugging Face training container
# peft, bitsandbytes, accelerate, huggingface_hub, pandas are already installed
# This is a large 35 Gb image

FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-training:2.5.1-transformers4.49.0-gpu-py311-cu124-ubuntu22.04

RUN python -m pip install --upgrade pip setuptools wheel packaging

# Qwen 3 requires transformers >=4.51.3
RUN pip install --no-cache-dir --upgrade "transformers==5.3.0"

# Flash attention is not installed in the default container 
# Common values: 8.0 (A100), 8.6 (RTX 3090/A4000), 8.9 (RTX 4090/L4), 9.0 (H100)
# Passed directly into the RUN command to ensure the compiler picks them up.
# Added --no-deps so it strictly compiles flash-attn and doesn't ruin the existing PyTorch installation by reinstalling it
# Lowered MAX_JOBS to 2 so it only consumes ~10GB of RAM, easily fitting inside Docker Desktop's 16GB limit.
RUN MAX_JOBS=2 TORCH_CUDA_ARCH_LIST="8.9" pip install flash-attn \
    --force-reinstall \
    --no-build-isolation \
    --no-cache-dir \
    --no-deps