name: CI Pipeline

on:
  # Branch protection rules prevent push to protected branches
  # push:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'README.md'
      - 'diagram/**'
      - 'docs/**'

jobs:
  ci-build-test:
    runs-on: ubuntu-latest

    # Environment variables for this job
    env:
      # Variables
      AWS_REGION: "us-east-1"
      ENV: "dev-ci"
      IMAGE_TAG: pr-${{ github.event.pull_request.number }} #${{ github.sha }}
      TF_VAR_IMAGE_TAG: pr-${{ github.event.pull_request.number }}

      # Secrets (used more than once)
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      TF_VAR_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python3.11
      uses: actions/setup-python@v7
      with:
        python-version: "3.11"
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        uv pip sync --system requirements_ci.txt
    - name: Lint Python with flake8
      run: |
        # stop the build if there are errors
        flake8 src/ setup/ images/
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Setup Terraform CLI 1.16.2
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.16.2"
    - name: Setup TF project with S3 backend
      run: |
        terraform -chdir=Terraform/ init \
          -backend-config="backend/dev-ci.hcl"
    - name: Validate and format Terraform
      run: |
        cd Terraform
        terraform validate
        terraform fmt
    - name: Download lambda appconfig layer
      run: |
        cd ./images/lambda_gateway
        chmod +x download_appconfig_layer.sh
        ./download_appconfig_layer.sh
    - name: Build docker images
      run: |
        chmod +x ./images/build_ecr.sh
        ./images/build_ecr.sh
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.10.0
    - name: Setup Kubernetes ECR Secret file
      run: |
        cat <<EOF > ./k8s/credentials
        [default]
        aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region=${{ env.AWS_REGION }}
        EOF
    - name: Install MLRun via Helm
      run: |
        chmod +x ./k8s/install.sh
        ./k8s/install.sh
        rm ./k8s/credentials
    - name: Terraform apply
      run: |
        terraform -chdir=Terraform/ apply \
        -var-file="dev-ci.tfvars" \
        --auto-approve
    # - name: Setup MLRun project
    #   run: python ./setup/setup_project.py
    - name: Expose MLRun API to Github Runner
      run: |
        # Run port-forward in the background (&) so it doesn't block the next CI steps
        kubectl port-forward -n mlrun svc/mlrun-api 30070:8080 > /dev/null 2>&1 &
        
        # Wait a few seconds for the connection to establish
        sleep 5
    - name: List MLRun Services
      run: kubectl get svc -n mlrun
    - name: Build MLRun functions
      env: 
        FEATURE_BRANCH: ${{ github.head_ref }}
        MLRUN_AWS_ROLE_ARN: ${{ secrets.MLRUN_AWS_ROLE_ARN }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python ./setup/build_functions.py
    - name: Run tests
      run: |
        pytest --capture=no
        echo "---> Unit tests passed"
    - name: Destroy terraform
      if: always()
      run: |
        terraform -chdir=Terraform/ destroy \
        -var-file="dev-ci.tfvars" \
        --auto-approve
      
    

